### ISSUE TITLE
Esri map doesnt load in electron when using arcgis version > 4.7 and `nodeIntegration: true`

### ISSUE THREAD

**Issue by progravi** [Esri/esri-loader#147]
### Expected behavior
I have to use arcgis version 4.9 or greater to display the insterstate milemarkers. when i updated the arcgis version the milemarkers work fine in the browser but in electron i get a console error and the esri map does not load.

### Actual behavior
I get an error in electron when using arcgis version 4.9, works fine in web and electron when using version 4.7.

![image](https://user-images.githubusercontent.com/4451741/50643709-d525f600-0f3c-11e9-84fc-be54c9baa210.png)

### Steps to reproduce the behavior
I have created a codesandbox sample which shows the mile markers work correctly  using arcgis version 4.9 in the browser, but electron get an error.
https://codesandbox.io/s/jp4x2l85nv

use npm run electron to open the app in electron, the main.js file has code for it to run in electron, i am not sure how i can simulate that in codesandbox. i used create-react-app template to be able to run the app in electron .

**Comment by andygup** [comment]
I was able to repro using Electron `4.0.1`. The node process integration seems to be causing problems with ArcGIS JS API 4.8+ and I'm not sure why. I was able to get it working by changing one line in `main.js` as follows:
```
 mainWindow = new BrowserWindow({width: 800, height: 600, webPreferences: {nodeIntegration: false}})
```
And, here is my `index.html`. I had to eliminate the node specific stuff...scroll down to CAVEATS for additional info.

```
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <title>Hello esri-loader!</title>
    <link rel="stylesheet" href="https://js.arcgis.com/4.10/esri/css/main.css">

    <script src="https://js.esri.com/4.10/"></script>
  </head>
  <body>
    <h1>Hello esri-loader!</h1>

    <!-- a DOM node to hold the map view -->
    <div id="viewDiv" style="height: 400px"></div>

    <script>
      // This isn't required, but I consider it a best practice
      document.addEventListener('DOMContentLoaded',pageLoaded);

      function pageLoaded(){
        console.log('The page is loaded');

        require([
          "esri/Map",
          "esri/views/MapView"
        ], function(Map, MapView) {

          console.log("ArcGIS require() loaded.");

          let map = new Map({
            basemap: "streets"
          });

          let view = new MapView({
            container: "viewDiv",
            map: map,
            zoom: 4,
            center: [15, 65]
          });

        });
      }
    </script>
  </body>
</html>

```

**CAVEATS:**
1) If you disable Node integration you won't be to use the pattern `const xyz = require('something');`
2) This will work as long as you don't need access to node process or IPC because those are only available in Node context. FYI, at `5.0.0` the `nodeIntegration` will default to `false`.  Reference from the current master branch: https://github.com/electron/electron/blob/master/docs/api/browser-window.md#new-browserwindowoptions

**Comment by progravi** [comment]
Thanks Andy, but we are using some node modules using require syntax and that failing as you mentioned when we set the nodeIntegration to false.

**Comment by andygup** [comment]
Gotcha. The only other suggestion I have is to use something like electron-webpack and precompile with babel.

If you figure out another way definitely let us know.

https://github.com/electron-userland/electron-webpack

**Comment by tomwayson** [comment]
FYI - I don't think this will help you, @progravi, but a slight alternative to @andy's example above would be instead of loading the JSAPI via `<script>` tag in `index.html`, you load use esri-loader via `<script>` tag from the CDN as I did here:

https://github.com/tomwayson/esri-loader-electron/commit/0cb237ca3ce15a291ac0c6c7bc4fa4f95b3564cd

Of course you'd have to replace `require('./renderer.js')` w/ a script tag that loads it.

Really though, anything like electron-webpack that bundles your code before executing it should work. I think it's interesting that `nodeIntergation` will default to `false` going forward. I wonder if electron is going to prescribe that kind of bundling.

**Comment by tomwayson** [comment]
@progravi 

Another thing you might try is renaming node's `require()` as per these docs:

https://electronjs.org/docs/all#i-can-not-use-jqueryrequirejsmeteorangularjs-in-electron

**Comment by progravi** [comment]
> Thanks @andy.
> 
> Did you by chance try `nodeIntegrationInWorker: false` w/ `nodeIntegration: true`? I just noticed the `nodeIntegrationInWorker` option in the link you sent.

that didnt work tom, seeing the error i intially posted in electron, will try using the electron webpack

**Comment by andygup** [comment]
I also wondered about trying some variation of using `preload`, but ran out of time.

**Comment by progravi** [comment]
@tomwayson @andygup  - I have tried using electron webpack to package the app code i posted and get the same console error i was seeing before.

**Comment by tomwayson** [comment]
I'm sorry to hear that @progravi. Have you had a chance to try any of the other suggestions above?

**Comment by progravi** [comment]
> I'm sorry to hear that @progravi. Have you had a chance to try any of the other suggestions above?

Hey Tom - The rename of require didnt work, and i am not very sure how to implement this (set nodeIntegration: false and possibly try preload) as we are having the same code base to work in web browser and electron

**Comment by andygup** [comment]
@progravi have you considered using `BrowserView`?

**Comment by progravi** [comment]
> @progravi have you considered using `BrowserView`?

Hey @andygup  - tried browserview same console error.

**Comment by andygup** [comment]
@progravi interesting...BrowserView must still be using node.js for parsing, which will throw errors. Maybe there is some other way to make this work that doesn't involve parsing the ArcGIS JS API library in node? 

In comparison we know that our JS API works directly in WebView and all the major browsers, so BrowserView must be a highly customized look-alike using node under the hood.

We took a look at some of the differences in our library build between 4.7 and 4.9 and didn't see any major differences that would be a red flag.

**Comment by schontz** [comment]
I ran into something like this and the root of the issue was that dojo thought it was running in node (it kind of is...). I was able to edit my `dojoConfig` to get it working:

```
dojoConfig = {
  async: true,
  has: {
    'host-node': false,
    'dojo-sync-loader': false
}
```
(I'm not sure if all of those values are required.) I happen to have `nodeIntegration` disabled, but I do have a `preload` script, which does have access to `require`:

```
process.once('loaded', () => {
	window.electronRequire = require;
});
```

That enables me to use `electronRequire('some-node-module')` in the renderer.

Hope that helps.

**Comment by andygup** [comment]
Thanks @schontz. Good info!

**Comment by jwasilgeo** [comment]
I’m curious if anyone is still encountering this situation while using more recent JSAPI versions. Any updates or thoughts @progravi @schontz?

**Comment by schontz** [comment]
I haven't changed my current setup, but I think it is still good practice to not expose `require()` in that way for the sake of security and any other code that may be looking for `require()`.

**Comment by andygup** [comment]
Closing. For new projects you might consider looking at our ES modules build: https://developers.arcgis.com/javascript/latest/guide/es-modules/
