### ISSUE TITLE
Swipe action on mobile devices cause mapView center jump to unpredictable position

### ISSUE THREAD

**Issue by degerio** [Esri/esri-loader#212]
### Expected behavior

- Move map on mobile using finger and have smooth movement.
- Angular8, esri-loader 2.13.0 with default library version of 4.14

### Actual behavior

- Moving 50m on California with swipe leads map to Ocean, next swipe move to Antarctica 
- No console errors

### Steps to reproduce the behavior

Download example from GIT ( doesn't matter webpack or esri-loader ), switch version to 4.14
In terminal do ng serve or build, try swipe.

v.4.13 and lower works correct.

**Comment by andygup** [comment]
@degerio I'm not able to reproduce the issue on iPhone 10/Safari or Pixel 2/Android 10/Chrome using Stackblitz. I haven't tried running it locally yet. Here's my sample app: https://stackblitz.com/edit/angular-cli-esri-map3 that you can test against.

Sometimes the browser cache can mess things up. Maybe restart your phone and clear your browser cache before trying again with my stackblitz example.

Can you provide the following info?
* Mobile phone model and operating system version 
* Browser and version

**Comment by degerio** [comment]
ok, I've found reason, in examples for component styles are defined as CSS with import url from esri.
My component had style 4.13 import but my component use SCSS.

CSS + import 4.12 / 4.13 / 4.14 -> ok
SCSS + import 4.12 / 4.13 -> failed
SCSS + import 4.14 -> ok

You can try to reproduce bug with invalid behavior on your own doing build or serve.
https://github.com/degerio/esri-loader-issue-212

**Comment by andygup** [comment]
I'm not sure what's going on. It's also possible there was a mismatch between the JS API version and it's designated CSS version. We'll be making a few changes in the next upcoming update of the `angular-cli-esri-map` repo and we'll provide additional documentation that should help with at least part of this issue.

Since both CSS and SCSS work at 4.14, which is the latest version of the JS API at this time, I'm going to consider this issue resolved for now.

If something else comes up let us know.
