### ISSUE TITLE
How to require geojsonlayer.js in a webpack app

### ISSUE THREAD

**Issue by ahmadalibaloch** [Esri/esri-loader#27]
`dojoRequire(['geojsonlayer.js']` is looking for geojsonlayer.js on a path on server. How to bundle this with webpack?
https://github.com/Esri/geojson-layer-js

**Comment by tomwayson** [comment]
I think you'd have to either use a relative path name (`'./geojsonlayer.js'`) or set up a [path/package in your dojoConfig](https://github.com/tomwayson/esri-webpack-babel#dojo-lbraries) so that the dojo loader can resolve that module. I suggest you get that working outside of webpack/esri-loader first.

**Comment by tomwayson** [comment]
See also this similar issue: https://github.com/tomwayson/angular-esri-loader/issues/24

**Comment by tomwayson** [comment]
BTW - this should be easier since #40, see https://github.com/Esri/esri-loader#configuring-dojo

**Comment by ahmadalibaloch** [comment]
I was not successful in this at that time, I left it. I will try again sometime.

**Comment by tomwayson** [comment]
Sounds good.

I should have mentioned in my original response that b/c geojsonlayer.js is a Dojo AMD module, it will not be "bundled with webpack." What I'm proposing is that you configure Dojo to know how to be able to load it just like it loads the modules of the ArcGIS API.

**Comment by tomwayson** [comment]
@ahmadalibaloch I'm assuming you've resolved your issue and closing this for now. Feel free to re-open if needed.
