### ISSUE TITLE
angular 2 esri-loadr multipleDefine  error 

### ISSUE THREAD

**Issue by AlexOliinyk1** [Esri/esri-loader#29]
I don't why but I have some issue with multipledefine and I don't know how to resolve it. 

My index.html looks like this 

![image](https://user-images.githubusercontent.com/10448723/29877623-ce40b396-8da8-11e7-9250-243de56cbd55.png)

I got this error in the console google chrome 
 
![image](https://user-images.githubusercontent.com/10448723/29877657-e894c8f4-8da8-11e7-87be-a781f3e39f76.png)

Logic when I call esri loader looks like this 
![image](https://user-images.githubusercontent.com/10448723/29877722-15e583e8-8da9-11e7-9178-720af1d487d8.png)

Thanks

**Comment by tomwayson** [comment]
It looks like your are using esri-loader directly in an Angular application and have hard coded the `<script src="https://js.arcgis.com/3.21/" ...>` tag in index.html. 

Unless you have a specific reason to do it that way, I'd recommend using [angular-esri-loader](https://www.npmjs.com/package/angular-esri-loader) (or [angular2-esri-loader](https://www.npmjs.com/package/angular2-esri-loader) if you are using Angular v2) and then following [these instructions](https://github.com/tomwayson/angular-esri-loader#usage). 

If you are still having a problem, you can open an issue [in that repository](https://github.com/tomwayson/angular-esri-loader/issues).

**Comment by AlexOliinyk1** [comment]
@tomwayson  opened https://github.com/tomwayson/angular-esri-loader/issues/30

**Comment by AlexOliinyk1** [comment]
@tomwayson https://github.com/Esri/esri-loader#using-your-own-script-tag how about this approach ?

**Comment by AlexOliinyk1** [comment]
@tomwayson  this functionality already implemented to check multiple times loading script works ? https://github.com/Esri/esri-loader/pull/22

**Comment by tomwayson** [comment]
Yes, that approach should still work. I haven't tried it in a while. I intended for that kind of low level approach to be used outside of framework. If you use it with a framework, then you are responsible for understanding when Dojo has loaded, the framework's own lifecycles, the asynchronous nature of dojo module loading, and how to manage all the interactions between those.

However, when you're using a framework like Angular 2 that provides higher level abstractions like promises and dependency injection of singleton services, etc, you can benefit from using the wrapper library, in this case [angular2-esri-loader](https://www.npmjs.com/package/angular2-esri-loader). Also, I'd say that using the wrapper library is probably more the norm, and you're more likely to benefit from someone else's experience.

That said, do whatever works. It seems from above that the bring your own script tag approach isn't working for you, which is why I suggested trying the wrapper library.

**Comment by tomwayson** [comment]
Honestly if you are going to hard code the script tag on the page, why not get rid of esri-loader entirely? It's not doing much (if anything) for you. You might as well uninstall esri-loader and replace `this.esri.laoder.dojoRequire(...)` with `window.require()`.

**Comment by AlexOliinyk1** [comment]
@tomwayson  based on this https://github.com/tomwayson/angular-esri-loader/issues/30
can be closed

**Comment by tomwayson** [comment]
great. thanks.
