### ISSUE TITLE
Server rendering problem

### ISSUE THREAD

**Issue by tgeorges** [Esri/esri-loader#64]
Hi esri-loader team !

I experienced a bad issue when using version from 1.5.x with React server rendering : window.Promise was not defined.

The workaround was quite simple but not esthetic...
Maybe you can fix it and make this library server rendering aware ?

=> link to the problem : 

https://github.com/Esri/esri-loader/blob/21e7323c643a7cba85471edc635b58c940b577c2/src/esri-loader.ts#L80

**Comment by tomwayson** [comment]
Thanks @tgeorges 

I would like to make this work, but unfortunately I don't have a server rendered react app nor the relevant expertise to test with.

If you manage to get this working and want to make a pull request w/ the fix, I'd be glad to review/merge assuming I can reason about the changes and that tests pass.

**Comment by andygup** [comment]
@tgeorges did your code work with a previous version of `esri-loader`? BTW `window` isn't available on the server. You may have to cut a special version of this library to bypass that. Here are some suggestions: https://github.com/webpack/react-starter/issues/37

**Comment by tomwayson** [comment]
That's a good question @andygup, I can see how it would have worked w/ an older version and not this one, and that's what I was assuming, but would be good to confirm from @tgeorges.

I neglected to mention before that I have a [WIP example of how to use esri-loader in an Ember Fastboot (server-rendered) app](https://github.com/tomwayson/esri-fastboot-example/pull/1). That [uses esri-loader 1.5^](https://github.com/Esri/ember-esri-loader/blob/8f85f282b9c4eb469981ccf4716d310c7f5675f3/package.json#L30). One difference w/ Ember is that the addon that wraps this library [explicitly overwrites the Promise implementation w/ Ember's RSVP](https://github.com/Esri/ember-esri-loader/blob/0c2460ed90032b30c190bf9b22e640be8a7a1eea/addon/services/esri-loader.js#L21). That said, I'm still a bit surprised the above line didn't cause an issue in Ember Fastboot b/c I believe that is executed before the code that overwrites it.

Which brings up a point that generally speaking if you want to use this in a server-rendered application you can **not** load JSAPI modules or render a map on the server side (b/c you can't run Dojo in node). So, any calls to the actual methods in this library need to be gated to a browser environment. For example, in my Fastboot example, I [load the modules and create the map inside the component's `didInsertElement()` lifecycle hook](https://github.com/tomwayson/esri-fastboot-example/pull/1/files#diff-86492abc29bcf5768056d6d2482e16feR14) (which is equivalent to React's `componentDidMount()`) because that hook is not executed on the server. I presume if @tgeorges had this working before, he was doing something similar.

We could implement a naive fix like `Promise: window && window['Promise']` or `Promise: isBrowser && window['Promise']` [as suggested in the thread @andygup linked to](https://github.com/webpack/react-starter/issues/37#issuecomment-104304128). However, I'm reluctant to do that w/o actually being able to test it in a server-side environment where the current code is failing. Again, if @tgeorges wants to try that, and can confirm it works, and makes a PR, and it doesn't break in a browser, I'll be glad to merge it.

**Comment by tgeorges** [comment]
Hi @tomwayson  and @andygup ! Thanks for your suggestions :-)
For now I have foolishly create that global context on the server side to ensure it works correctly : 

```js

import Promise from 'bluebird';

global.window = global.window || {};
global.window.Promise = global.window.Promise || Promise;

```

Its a not elegant solutions but working for now. What I can suggest is to use an universal implementation of Promises (working in both client and server sides) as a dependency.

What is your opinion ?

**Comment by tomwayson** [comment]
Thanks @tgeorges 

I [deliberately chose not to take a dependency on a promise library](https://github.com/Esri/esri-loader/issues/8#issuecomment-341567186). I don't think that is needed to solve this problem.

I think we can do what I suggest above. `esriLoader.utils.Promise` will be empty on the server, but it should never actually be invoked on the server, so that should be OK.

**Comment by tgeorges** [comment]
Ok I understand, do you need some support for that ? I think a simple test in your library to ensure that browser window is defined is enough

**Comment by tomwayson** [comment]
Well, since I can't currently reproduce the problem, I can't be sure that my suggestion would fix it. I'd prefer to have that confirmation before making that change and cutting a release. 

Is your application's code available somewhere so I can try it myself?

Alternatively would you be able to reproduce the problem in a minimal boilerplate universal react app, or at least point me to one that approximates your application's setup?

Left to my own devices I'd just try creating an [app via Next.js](https://hackernoon.com/next-js-react-server-side-rendering-done-right-f9700078a3b6) b/c that looks like the fastest way for me to get something up and running, but I'm not sure if that would accurately approximate how your app is rendered server-side.

**Comment by tgeorges** [comment]
Hi @tomwayson,
sorry for the delay. My code cannot be published easily but I can suggest you a good starter kit from  kriasoft to reproduce the problem.
You can find it here : https://github.com/kriasoft/react-starter-kit
To reproduce it, simply declare a Map component in component hierarchy, and use it in a page (for exemple Home) in router hierarchy.

In this component, load Esri Js with your library, and try showing it directly : it will be server rendered and you will touch the problem :-)

I will be unavailable next week but I can find some time the 1st week of 2018 to help you reproduce that

Cheers and happy XMas time :-)

**Comment by tomwayson** [comment]
@tgeorges this should be fixed by installing esri-loader@^1.6.0

**Comment by tomwayson** [comment]
FYI - see https://github.com/tomwayson/esri-loader-react-starter-kit

**Comment by Biboba** [comment]
Hi,

It is a pity that map cannot be rendered at the server side as well.
@tomwayson mentionned that it is because 'b/c you can't run Dojo in node' but isn't it doable as mentionned in the documentation:
http://dojotoolkit.org/documentation/tutorials/1.10/node/

Thanks !

**Comment by tomwayson** [comment]
@Biboba I've updated my comment above to be more accurate: "you can't run the ArcGIS API for JavaScript in node." I haven't tried it myself, but server-side rendering JavaScript maps is not trivial even w/o the challenges of trying to load Dojo modules.

Instead, I'd look into doing something like rendering a static image on the server and replacing that w/ the map once the ArcGIS API is loaded in the browser.

**Comment by Biboba** [comment]
@tomwayson Thanks for your precisions !
